2023-01-08 19:00:28.218658: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /home1/08589/hvtran/.local/lib/python3.9/site-packages/cv2/../../lib64:/opt/apps/pmix/3.2.3/lib:/opt/apps/intel19/python3/3.9.7/lib:/opt/intel/compilers_and_libraries_2020.4.304/linux/mpi/intel64/libfabric/lib:/opt/intel/compilers_and_libraries_2020.4.304/linux/mpi/intel64/lib/release:/opt/intel/compilers_and_libraries_2020.4.304/linux/mpi/intel64/lib:/opt/intel/debugger_2020/libipt/intel64/lib:/opt/intel/compilers_and_libraries_2020.1.217/linux/daal/lib/intel64_lin:/opt/intel/compilers_and_libraries_2020.1.217/linux/tbb/lib/intel64_lin/gcc4.8:/opt/intel/compilers_and_libraries_2020.1.217/linux/mkl/lib/intel64_lin:/opt/intel/compilers_and_libraries_2020.1.217/linux/ipp/lib/intel64:/opt/intel/compilers_and_libraries_2020.1.217/linux/compiler/lib/intel64_lin:/opt/apps/gcc/9.4.0/lib64:/opt/apps/gcc/9.4.0/lib:/usr/lib64
2023-01-08 19:00:28.219111: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Setting up [LPIPS] perceptual loss: trunk [alex], v[0.1], spatial [off]
Loading model from: /home1/08589/hvtran/.local/lib/python3.9/site-packages/lpips/weights/v0.1/alex.pth
Namespace(is_training=0, device='cuda', dataset_name='mnist', train_data_paths='/work/08589/hvtran/ls6/ERA5_PredRNN-main/era5_train_1024002012_3_24hr.npz', valid_data_paths='/work/08589/hvtran/ls6/ERA5_PredRNN-main/era5_train_1024002012_3_24hr.npz', save_dir='/scratch/08589/hvtran/predrnn-pytorch/checkpoints/2012_predrnn_test_precip', gen_frm_dir='/scratch/08589/hvtran/predrnn-pytorch/checkpoints/2012_predrnn_test_precip', input_length=24, total_length=48, img_width=1440, img_height=720, img_channel=1, img_layers='2,1,0', concurent_step=14, use_weight=0, layer_weight='10,10,10,10,20,20', skip_time=1, wavelet='db1', center_enhance=False, layer_need_enhance=0, find_max=False, multiply=1.1, model_name='predrnn_v2', pretrained_model='/work/08589/hvtran/ls6/ERA5_PredRNN-main/model.ckpt-best-precip', num_hidden='460,460,460,460,460,460', filter_size=5, stride=1, patch_size=15, patch_size1=4, layer_norm=1, decouple_beta=0.05, reverse_scheduled_sampling=1, r_sampling_step_1=25000.0, r_sampling_step_2=50000, r_exp_alpha=2500, scheduled_sampling=1, sampling_stop_iter=50000, sampling_start_value=1.0, sampling_changing_rate=2e-05, lr=0.05, reverse_input=1, batch_size=1, max_iterations=4000, display_interval=10, test_interval=200, snapshot_interval=200, num_save_samples=10, n_gpu=1, visual=0, visual_path='./decoupling_visual', injection_action='concat', conv_on_input=0, res_on_conv=0, num_action_ch=4, is_static=0, is_scale=0, out_scale1='', out_scale2='', in_scale1='', in_scale2='', noise_val=0, out_channel=5, stat_layers=8, stat_layers2=5, out_weights='', curr_best_loss=100000.0, isloss=1, is_logscale=0, is_WV=1)
Initializing models
load model: /work/08589/hvtran/ls6/ERA5_PredRNN-main/model.ckpt-best-precip
clips
(2, 14, 2)
dims
(1, 3)
input_raw_data
(336, 1, 720, 1440)
2023-01-08 19:05:17 test...
/work/08589/hvtran/ls6/miniconda3/lib/python3.9/site-packages/torch/nn/functional.py:718: UserWarning: Named tensors and all their associated APIs are an experimental feature and subject to change. Please do not use them for anything important until they are released as stable. (Triggered internally at  /pytorch/c10/core/TensorImpl.h:1156.)
  return torch.max_pool2d(input, kernel_size, stride, padding, dilation, ceil_mode)
/work/08589/hvtran/ls6/ERA5_PredRNN-main/predrnn-pytorch/core/trainer.py:144: FutureWarning: `multichannel` is a deprecated argument name for `structural_similarity`. It will be removed in version 1.0. Please use `channel_axis` instead.
  score, _ = compare_ssim(pred_frm[b], real_frm[b], full=True, multichannel=True)
Traceback (most recent call last):
  File "/work/08589/hvtran/ls6/ERA5_PredRNN-main/predrnn-pytorch/run1.py", line 290, in <module>
    test_wrapper(model)
  File "/work/08589/hvtran/ls6/ERA5_PredRNN-main/predrnn-pytorch/run1.py", line 270, in test_wrapper
    trainer.test(model, test_input_handle, args, 'test_result')
  File "/work/08589/hvtran/ls6/ERA5_PredRNN-main/predrnn-pytorch/core/trainer.py", line 75, in test
    test_ims = test_input_handle.get_batch()
  File "/work/08589/hvtran/ls6/ERA5_PredRNN-main/predrnn-pytorch/core/data_provider/mnist.py", line 170, in get_batch
    input_seq = self.input_batch()
  File "/work/08589/hvtran/ls6/ERA5_PredRNN-main/predrnn-pytorch/core/data_provider/mnist.py", line 132, in input_batch
    input_batch[i, :self.current_input_length*self.concurent_step, :, :, :] = data_slice
ValueError: could not broadcast input array from shape (312,720,1440,1) into shape (336,720,1440,1)
2023-01-08 19:07:16.569289: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /home1/08589/hvtran/.local/lib/python3.9/site-packages/cv2/../../lib64:/opt/apps/pmix/3.2.3/lib:/opt/apps/intel19/python3/3.9.7/lib:/opt/intel/compilers_and_libraries_2020.4.304/linux/mpi/intel64/libfabric/lib:/opt/intel/compilers_and_libraries_2020.4.304/linux/mpi/intel64/lib/release:/opt/intel/compilers_and_libraries_2020.4.304/linux/mpi/intel64/lib:/opt/intel/debugger_2020/libipt/intel64/lib:/opt/intel/compilers_and_libraries_2020.1.217/linux/daal/lib/intel64_lin:/opt/intel/compilers_and_libraries_2020.1.217/linux/tbb/lib/intel64_lin/gcc4.8:/opt/intel/compilers_and_libraries_2020.1.217/linux/mkl/lib/intel64_lin:/opt/intel/compilers_and_libraries_2020.1.217/linux/ipp/lib/intel64:/opt/intel/compilers_and_libraries_2020.1.217/linux/compiler/lib/intel64_lin:/opt/apps/gcc/9.4.0/lib64:/opt/apps/gcc/9.4.0/lib:/usr/lib64
2023-01-08 19:07:16.569371: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Setting up [LPIPS] perceptual loss: trunk [alex], v[0.1], spatial [off]
Loading model from: /home1/08589/hvtran/.local/lib/python3.9/site-packages/lpips/weights/v0.1/alex.pth
Namespace(is_training=0, device='cuda', dataset_name='mnist', train_data_paths='/work/08589/hvtran/ls6/ERA5_PredRNN-main/era5_train_1024002012_3_24hr.npz', valid_data_paths='/work/08589/hvtran/ls6/ERA5_PredRNN-main/era5_train_1024002012_3_24hr.npz', save_dir='/scratch/08589/hvtran/predrnn-pytorch/checkpoints/2012_predrnn_test_wind', gen_frm_dir='/scratch/08589/hvtran/predrnn-pytorch/checkpoints/2012_predrnn_test_wind', input_length=24, total_length=48, img_width=1440, img_height=720, img_channel=1, img_layers='0,1,2', concurent_step=14, use_weight=0, layer_weight='10,10,10,10,20,20', skip_time=1, wavelet='db1', center_enhance=False, layer_need_enhance=0, find_max=False, multiply=1.1, model_name='predrnn_v2', pretrained_model='/work/08589/hvtran/ls6/ERA5_PredRNN-main/model.ckpt-best-wind', num_hidden='460,460,460,460,460,460', filter_size=5, stride=1, patch_size=15, patch_size1=4, layer_norm=1, decouple_beta=0.05, reverse_scheduled_sampling=1, r_sampling_step_1=25000.0, r_sampling_step_2=50000, r_exp_alpha=2500, scheduled_sampling=1, sampling_stop_iter=50000, sampling_start_value=1.0, sampling_changing_rate=2e-05, lr=0.05, reverse_input=1, batch_size=1, max_iterations=4000, display_interval=10, test_interval=200, snapshot_interval=200, num_save_samples=10, n_gpu=1, visual=0, visual_path='./decoupling_visual', injection_action='concat', conv_on_input=0, res_on_conv=0, num_action_ch=4, is_static=0, is_scale=0, out_scale1='', out_scale2='', in_scale1='', in_scale2='', noise_val=0, out_channel=5, stat_layers=8, stat_layers2=5, out_weights='', curr_best_loss=100000.0, isloss=1, is_logscale=0, is_WV=1)
Initializing models
load model: /work/08589/hvtran/ls6/ERA5_PredRNN-main/model.ckpt-best-wind
clips
(2, 14, 2)
dims
(1, 3)
input_raw_data
(336, 1, 720, 1440)
2023-01-08 19:07:41 test...
/work/08589/hvtran/ls6/miniconda3/lib/python3.9/site-packages/torch/nn/functional.py:718: UserWarning: Named tensors and all their associated APIs are an experimental feature and subject to change. Please do not use them for anything important until they are released as stable. (Triggered internally at  /pytorch/c10/core/TensorImpl.h:1156.)
  return torch.max_pool2d(input, kernel_size, stride, padding, dilation, ceil_mode)
/work/08589/hvtran/ls6/ERA5_PredRNN-main/predrnn-pytorch/core/trainer.py:144: FutureWarning: `multichannel` is a deprecated argument name for `structural_similarity`. It will be removed in version 1.0. Please use `channel_axis` instead.
  score, _ = compare_ssim(pred_frm[b], real_frm[b], full=True, multichannel=True)
Traceback (most recent call last):
  File "/work/08589/hvtran/ls6/ERA5_PredRNN-main/predrnn-pytorch/run1.py", line 290, in <module>
    test_wrapper(model)
  File "/work/08589/hvtran/ls6/ERA5_PredRNN-main/predrnn-pytorch/run1.py", line 270, in test_wrapper
    trainer.test(model, test_input_handle, args, 'test_result')
  File "/work/08589/hvtran/ls6/ERA5_PredRNN-main/predrnn-pytorch/core/trainer.py", line 75, in test
    test_ims = test_input_handle.get_batch()
  File "/work/08589/hvtran/ls6/ERA5_PredRNN-main/predrnn-pytorch/core/data_provider/mnist.py", line 170, in get_batch
    input_seq = self.input_batch()
  File "/work/08589/hvtran/ls6/ERA5_PredRNN-main/predrnn-pytorch/core/data_provider/mnist.py", line 132, in input_batch
    input_batch[i, :self.current_input_length*self.concurent_step, :, :, :] = data_slice
ValueError: could not broadcast input array from shape (312,720,1440,1) into shape (336,720,1440,1)
2023-01-08 19:09:27.595699: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /home1/08589/hvtran/.local/lib/python3.9/site-packages/cv2/../../lib64:/opt/apps/pmix/3.2.3/lib:/opt/apps/intel19/python3/3.9.7/lib:/opt/intel/compilers_and_libraries_2020.4.304/linux/mpi/intel64/libfabric/lib:/opt/intel/compilers_and_libraries_2020.4.304/linux/mpi/intel64/lib/release:/opt/intel/compilers_and_libraries_2020.4.304/linux/mpi/intel64/lib:/opt/intel/debugger_2020/libipt/intel64/lib:/opt/intel/compilers_and_libraries_2020.1.217/linux/daal/lib/intel64_lin:/opt/intel/compilers_and_libraries_2020.1.217/linux/tbb/lib/intel64_lin/gcc4.8:/opt/intel/compilers_and_libraries_2020.1.217/linux/mkl/lib/intel64_lin:/opt/intel/compilers_and_libraries_2020.1.217/linux/ipp/lib/intel64:/opt/intel/compilers_and_libraries_2020.1.217/linux/compiler/lib/intel64_lin:/opt/apps/gcc/9.4.0/lib64:/opt/apps/gcc/9.4.0/lib:/usr/lib64
2023-01-08 19:09:27.595771: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Setting up [LPIPS] perceptual loss: trunk [alex], v[0.1], spatial [off]
Loading model from: /home1/08589/hvtran/.local/lib/python3.9/site-packages/lpips/weights/v0.1/alex.pth
Namespace(is_training=0, device='cuda', dataset_name='mnist', train_data_paths='/work/08589/hvtran/ls6/ERA5_PredRNN-main/era5_train_1024002012_3_24hr.npz', valid_data_paths='/work/08589/hvtran/ls6/ERA5_PredRNN-main/era5_train_1024002012_3_24hr.npz', save_dir='/scratch/08589/hvtran/predrnn-pytorch/checkpoints/2012_predrnn_test_sea_press', gen_frm_dir='/scratch/08589/hvtran/predrnn-pytorch/checkpoints/2012_predrnn_test_sea_press', input_length=24, total_length=48, img_width=1440, img_height=720, img_channel=1, img_layers='1,0,2', concurent_step=14, use_weight=0, layer_weight='10,10,10,10,20,20', skip_time=1, wavelet='db1', center_enhance=False, layer_need_enhance=0, find_max=False, multiply=1.1, model_name='predrnn_v2', pretrained_model='/work/08589/hvtran/ls6/ERA5_PredRNN-main/model.ckpt-best-sea_press', num_hidden='256,256,256,256', filter_size=5, stride=1, patch_size=15, patch_size1=4, layer_norm=1, decouple_beta=0.05, reverse_scheduled_sampling=1, r_sampling_step_1=25000.0, r_sampling_step_2=50000, r_exp_alpha=2500, scheduled_sampling=1, sampling_stop_iter=50000, sampling_start_value=1.0, sampling_changing_rate=2e-05, lr=0.05, reverse_input=1, batch_size=1, max_iterations=4000, display_interval=10, test_interval=200, snapshot_interval=200, num_save_samples=10, n_gpu=1, visual=0, visual_path='./decoupling_visual', injection_action='concat', conv_on_input=0, res_on_conv=0, num_action_ch=4, is_static=0, is_scale=0, out_scale1='', out_scale2='', in_scale1='', in_scale2='', noise_val=0, out_channel=5, stat_layers=8, stat_layers2=5, out_weights='', curr_best_loss=100000.0, isloss=1, is_logscale=0, is_WV=0)
Initializing models
load model: /work/08589/hvtran/ls6/ERA5_PredRNN-main/model.ckpt-best-sea_press
clips
(2, 14, 2)
dims
(1, 3)
input_raw_data
(336, 1, 720, 1440)
2023-01-08 19:09:48 test...
/work/08589/hvtran/ls6/miniconda3/lib/python3.9/site-packages/torch/nn/functional.py:718: UserWarning: Named tensors and all their associated APIs are an experimental feature and subject to change. Please do not use them for anything important until they are released as stable. (Triggered internally at  /pytorch/c10/core/TensorImpl.h:1156.)
  return torch.max_pool2d(input, kernel_size, stride, padding, dilation, ceil_mode)
/work/08589/hvtran/ls6/ERA5_PredRNN-main/predrnn-pytorch/core/trainer.py:144: FutureWarning: `multichannel` is a deprecated argument name for `structural_similarity`. It will be removed in version 1.0. Please use `channel_axis` instead.
  score, _ = compare_ssim(pred_frm[b], real_frm[b], full=True, multichannel=True)
Traceback (most recent call last):
  File "/work/08589/hvtran/ls6/ERA5_PredRNN-main/predrnn-pytorch/run1.py", line 290, in <module>
    test_wrapper(model)
  File "/work/08589/hvtran/ls6/ERA5_PredRNN-main/predrnn-pytorch/run1.py", line 270, in test_wrapper
    trainer.test(model, test_input_handle, args, 'test_result')
  File "/work/08589/hvtran/ls6/ERA5_PredRNN-main/predrnn-pytorch/core/trainer.py", line 75, in test
    test_ims = test_input_handle.get_batch()
  File "/work/08589/hvtran/ls6/ERA5_PredRNN-main/predrnn-pytorch/core/data_provider/mnist.py", line 170, in get_batch
    input_seq = self.input_batch()
  File "/work/08589/hvtran/ls6/ERA5_PredRNN-main/predrnn-pytorch/core/data_provider/mnist.py", line 132, in input_batch
    input_batch[i, :self.current_input_length*self.concurent_step, :, :, :] = data_slice
ValueError: could not broadcast input array from shape (312,720,1440,1) into shape (336,720,1440,1)
